### ISSUE TITLE
error adding package to Julia 1.1

### ISSUE THREAD

**Issue by ezgikurt** [sglyon/ORCA.jl#8]
Hi, I just installed a fresh version of Julia 1.1 (finally updating from 0.6.4) and trying to add my mainly used packages to it (which includes PlotlyJS which requires ORCA to save). 

I run into the following error which I think is related to the conda dependency. I can't figure out what I need to do:

```
Building ORCA → `C:\Users\usernam\.julia\packages\ORCA\ZfBvW\deps\build.log`
┌ Error: Error building `ORCA`:
│ Warning: 'plotly' already in 'channels' list, moving to the top
│
│ DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
│ Use 'conda create' to convert the directory to a conda environment.
│   target directory: C:\Users\usernam\.julia\packages\ORCA\ZfBvW\deps
│
│
│ [ Info: Running `conda config --add channels plotly --force` in C:\Users\usernam\.julia\packages\ORCA\ZfBvW\deps environ
ment
│ [ Info: Running `conda install -y plotly-orca` in C:\Users\usernam\.julia\packages\ORCA\ZfBvW\deps environment
│ ERROR: LoadError: failed process: Process(setenv(`'C:\Users\usernam\.julia\conda\3\Scripts\conda.exe' install -y plotly-
orca`,["USERDOMAIN_ROAMINGPROFILE=USR-LAPTOP", "HOMEPATH=\\Users\\usernam", "ProgramData=C:\\ProgramData", "ProgramW6432=
C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "APPDATA=C:\
\Users\\usernam\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=USR-LAPTOP", "OS=Windows_NT", "PROCESSOR_REVI
SION=8e0a", "TMP=C:\\Users\\usernam\\AppData\\Local\\Temp", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\Users\\usernam\\.ju
lia\\conda\\3\\Library\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WI
NDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Fil
es\\MATLAB\\MATLAB Production Server\\R2015a\\runtime\\win64;C:\\Program Files\\MATLAB\\MATLAB Production Server\\R2015a
\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Mana
gement Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Fil
es\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\Program Files\\TortoiseHg\\;C:\\Pr
ogram Files\\nodejs\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\usernam\\AppData\\Local\\Microsoft\\WindowsApps;C:\\User
s\\usernam\\AppData\\Local\\GitHubDesktop\\app-1.1.0\\resources\\app\\git\\cmd;C:\\Users\\usernam\\AppData\\Local\\julia-0.6
.4\\bin;C:\\Users\\usernam\\AppData\\Roaming\\npm;C:\\Users\\usernam\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\USR
k\\AppData\\Local\\atom\\bin;C:\\Users\\usernam\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\usernam\\AppDat
a\\Local\\Programs\\Python\\Python37;C:\\Users\\usernam\\AppData\\Local\\Programs\\Python\\Python37\\Scripts;", "COMPUTERN
AME=USR-LAPTOP", "USERNAME=usernam", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles
=C:\\Program Files\\Common Files", "CONDARC=C:\\Users\\usernam\\.julia\\packages\\ORCA\\ZfBvW\\deps\\condarc-julia.yml", "
USERPROFILE=C:\\Users\\usernam", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\Window
sPowerShell\\v1.0\\Modules", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\usernam\\.julia\\packages\\ORCA\\ZfBvW\\deps", "TEMP=C:\
\Users\\usernam\\AppData\\Local\\Temp", "SystemDrive=C:", "HOMEDRIVE=C:", "PYTHONIOENCODING=UTF-8", "LOCALAPPDATA=C:\\User
s\\usernam\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel", "DriverData=C:\\
Windows\\System32\\Drivers\\DriverData", "NUMBER_OF_PROCESSORS=8", "asl.log=Destination=file", "=::=::\\", "ComSpec=C:\\
WINDOWS\\system32\\cmd.exe", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\usernam\\OneDrive", "OneDriveConsumer=C:\\User
s\\usernam\\OneDrive", "ProgramFiles(x86)=C:\\Program Files (x86)", "LOGONSERVER=\\\\USR-LAPTOP", "CONDA_PREFIX=C:\\Users
\\usernam\\.julia\\packages\\ORCA\\ZfBvW\\deps", "windir=C:\\WINDOWS", "FPS_BROWSER_USER_PROFILE_STRING=Default", "JULIA_L
OAD_PATH=@;C:\\Users\\usernam\\AppData\\Local\\Temp\\jl_6378.tmp", "CommonProgramW6432=C:\\Program Files\\Common Files", "
ProgramFiles=C:\\Program Files", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OP
ENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
│  [4] run at .\process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::String) at C:\Users\usernam\.julia\packages\Conda\uQitS\src\Conda.jl:113
│  [6] add(::String, ::String) at C:\Users\usernam\.julia\packages\Conda\uQitS\src\Conda.jl:181
│  [7] top-level scope at none:0
│  [8] include at .\boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\usernam\.julia\packages\ORCA\ZfBvW\deps\build.jl:5
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\
Operations.jl:1075


```

**Comment by AlexYoooooo** [comment]
Ran into same issue when ran on ubuntu 14.03, however my friend with a windows machine seems fine :p

**Comment by sglyon** [comment]
Hmm, perhaps something got a bit funky in the package directories. 

Would you be open to experimenting a bit and deleting the whole directory for Julia 1.1 packages and trying again?

**Comment by ezgikurt** [comment]
Allright so I've deleted the packages directory first (to no avail). Then I deleted everything related to v1.1, uninstalled and installed again. Still there is the same error saying that this is not a conda environment. 

```
│ DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
│ Use 'conda create' to convert the directory to a conda environment.
│   target directory: C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps

│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
│  [4] run at .\process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::String) at C:\Users\ezgik\.julia\packages\Conda\CpuvI\src\Conda.jl:113
│  [6] add(::String, ::String) at C:\Users\ezgik\.julia\packages\Conda\CpuvI\src\Conda.jl:183
│  [7] top-level scope at none:0
│  [8] include at .\boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps\build.jl:5
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\
Operations.jl:1075
```

So I've tried doing what it says and used the anaconda prompt and turned the current directory into a conda directory using the following command:
```
(base) C:\Users\ezgik> conda create --prefix C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps

WARNING: A directory already exists at the target location 'C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps'
but it is not a conda environment.
Continue creating environment (y/[n])? y

Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\ezgik>conda activate


```

Then I've gone ahead and added ORCA. Builds okay now. However not the issue is in precompilation:

```
julia> using ORCA
[ Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
WARNING: eval into closed module Base:
Expr(:block, #= Symbol("C:\Users\ezgik\.julia\packages\Compat\hsya0\src\Compat.jl"):1891 =#, Expr(:call, :range, Expr(:p
arameters, Expr(:..., :kwargs)), :start, :stop) = Expr(:block, #= Symbol("C:\Users\ezgik\.julia\packages\Compat\hsya0\sr
c\Compat.jl"):1891 =#, Expr(:call, :range, Expr(:parameters, Expr(:kw, :stop, :stop), Expr(:..., :kwargs)), :start)))
  ** incremental compilation may be broken for this module **

WARNING: Method definition range(Any, Any) in module Base at range.jl:90 overwritten at C:\Users\ezgik\.julia\packages\C
ompat\hsya0\src\Compat.jl:1891.
WARNING: Method definition #range(Any, typeof(Base.range), Any, Any) in module Base overwritten.
ERROR: InitError: IOError: could not spawn `'C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps\orca_app\orca' server --port
=7982 --graph-only`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:400
 [2] setup_stdios(::getfield(Base, Symbol("##505#506")){Cmd}, ::Array{Any,1}) at .\process.jl:413
 [3] _spawn at .\process.jl:412 [inlined]
 [4] #open#514(::Bool, ::Bool, ::Function, ::Cmd, ::Base.DevNull) at .\process.jl:657
 [5] open at .\process.jl:648 [inlined] (repeats 2 times)
 [6] restart_server() at C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\src\ORCA.jl:80
 [7] __init__() at C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\src\ORCA.jl:90
 [8] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:633
 [9] _require_from_serialized(::String) at .\loading.jl:684
 [10] _require(::Base.PkgId) at .\loading.jl:967
 [11] require(::Base.PkgId) at .\loading.jl:858
 [12] require(::Module, ::Symbol) at .\loading.jl:853
during initialization of module ORCA
```

**Comment by dsweber2** [comment]
Ran into the same problem on Ubuntu 18.04, and  just did the conda bit in the way ezgikurt did. That worked for me, outside of compat generating warnings. But I've been getting those warnings quite a bit in other packages too.

**Comment by sglyon** [comment]
It sounds like this might be an issue with Conda.jl..  maybe we should open an issue over there?

**Comment by stevengj** [comment]
Using `env = @__DIR__` is problematic.

* Anaconda doesn't seem to like using an existing non-empty directory for an environment.  It works fine for me if you create an empty directory and pass that, however.
* Since the Pkg system now creates a new `ORCA` directory for *every* version, this means that every time you update ORCA.jl it will download a new copy of `plotly-orca`.

I would recommend just using `env = :_ORCA_jl_` so that it creates the environment under the shared `.julia/conda` directory.

**Comment by sglyon** [comment]
Excellent, I will give that a shot. Thanks for posting over here.

@ezgikurt @AlexYoooooo @dsweber2  I made that change on master. Would you mind checking out to the master branch (`]dev ORCA`) and trying to build/use?

**Comment by stevengj** [comment]
@sglyon, looks like you forgot to change the path for `orca_cmd = joinpath(@__DIR__, bindir, "orca")`?

**Comment by sglyon** [comment]
Yes thanks, I just noticed that also. 

Where will it put the binary now?

**Comment by sglyon** [comment]
On my machine it looks like it went to `~/.julia/conda/3/envs/_ORCA_jl_/bin`.

Will that always be true?

**Comment by stevengj** [comment]
You want `Conda.bin_dir(env)`.

**Comment by sglyon** [comment]
Thanks!

**Comment by AlexYoooooo** [comment]
> Excellent, I will give that a shot. Thanks for posting over here.
> 
> @ezgikurt @AlexYoooooo @dsweber2 I made that change on master. Would you mind checking out to the master branch (`]dev ORCA`) and trying to build/use?

what command in julia should I use to add dev version?

**Comment by ezgikurt** [comment]
Hi, thanks for the replies! The problems with the build are solved using the new version, but i still think there's something wrong because the following folder doesn't get added

```
ERROR: InitError: IOError: could not spawn `'C:\Users\ezgik\.julia\conda\3\envs\_ORCA_jl_\Library\bin\orca' server --por
t=7982 --graph-only`: no such file or directory (ENOENT)
```
i.e I don't have a directory called Library in _ORCA_jl. 

--
@AlexYoooooo the command is `dev ORCA` in the package mode.

**Comment by sglyon** [comment]
Thanks for reporting back. This sounds like it might be a problem with the `Conda.bindir` function.  Any chance you dig around inside the `C:\Users\ezgik\.julia\conda\3\envs\_ORCA_jl_\` folder and locate the `orca` binary? 

@stevengj any ideas  why the directory returned by `Conda.bindir(env)` doesn't exist?

**Comment by ezgikurt** [comment]
There is the orca.cmd file which I guess is supposed to run orca.exe, but the needed directory (orca app) is not there either.

Here is what I have in that directory:

```
 Directory of C:\Users\ezgik\.julia\conda\3\envs\_ORCA_jl_

01/02/2019  11:54    <DIR>          .
01/02/2019  11:54    <DIR>          ..
01/02/2019  11:54                 0 .nonadmin
01/02/2019  11:54    <DIR>          conda-meta
01/02/2019  12:05                37 condarc-julia.yml
01/02/2019  11:54                78 orca.cmd
               3 File(s)            115 bytes
               3 Dir(s)  232,098,164,736 bytes free
```

**Comment by AlexYoooooo** [comment]
I still get error message, I'll try again later today

(v1.1) pkg> dev ORCA
[ Info: Path `/home/alex/.julia/dev/ORCA` exists and looks like the correct package, using existing path
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
  [47be7bcc] + ORCA v0.2.0+ [`~/.julia/dev/ORCA`]
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [8f4d0f93] + Conda v1.2.0
  [47be7bcc] + ORCA v0.2.0+ [`~/.julia/dev/ORCA`]
  [81def892] + VersionParsing v1.1.3
(v1.1) pkg> build ORCA
  Building MbedTLS → `~/.julia/packages/MbedTLS/XkQiX/deps/build.log`
  Building Conda ──→ `~/.julia/packages/Conda/CpuvI/deps/build.log`
  Building ORCA ───→ `~/.julia/dev/ORCA/deps/build.log`
 Resolving package versions...
┌ Error: Error building `ORCA`: 
│ Warning: 'plotly' already in 'channels' list, moving to the top
│ Solving environment: ...working... failed
│ 
│ PackagesNotFoundError: The following packages are not available from current channels:
│ 
│   - plotly-orca
│ 
│ Current channels:
│ 
│   - https://conda.anaconda.org/plotly/linux-32
│   - https://conda.anaconda.org/plotly/noarch
│   - https://repo.anaconda.com/pkgs/main/linux-32
│   - https://repo.anaconda.com/pkgs/main/noarch
│   - https://repo.anaconda.com/pkgs/free/linux-32
│   - https://repo.anaconda.com/pkgs/free/noarch
│   - https://repo.anaconda.com/pkgs/r/linux-32
│   - https://repo.anaconda.com/pkgs/r/noarch
│   - https://repo.anaconda.com/pkgs/pro/linux-32
│   - https://repo.anaconda.com/pkgs/pro/noarch
│ 
│ To search for alternate channels that may provide the conda package you're
│ looking for, navigate to
│ 
│     https://anaconda.org
│ 
│ and use the search bar at the top of the page.
│ 
│ 
│ [ Info: Running `conda config --add channels plotly --file /home/alex/.julia/conda/3/envs/_ORCA_jl_/condarc-julia.yml --force` in _ORCA_jl_ environment
│ [ Info: Running `conda install -y plotly-orca` in _ORCA_jl_ environment
│ ERROR: LoadError: failed process: Process(setenv(`/home/alex/.julia/conda/3/bin/conda install -y plotly-orca`,["GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "DESKTOP_SESSION=ubuntu", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "UNITY_HAS_3D_SUPPORT=true", "LANG=en_CA.UTF-8", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "LESSOPEN=| /usr/bin/lesspipe %s", "UPSTART_EVENTS=xsession started", "OLDPWD=/home/alex", "GTK_IM_MODULE=ibus", "CONDA_PREFIX=/home/alex/.julia/conda/3/envs/_ORCA_jl_", "GNOME_KEYRING_PID=", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg", "COMPIZ_CONFIG_PROFILE=ubuntu", "COMPIZ_BIN_PATH=/usr/bin/", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "PYTHONIOENCODING=UTF-8", "XDG_SESSION_DESKTOP=ubuntu", "VTE_VERSION=4205", "GTK2_MODULES=overlay-scrollbar", "QT_IM_MODULE=ibus", "IM_CONFIG_PHASE=1", "UPSTART_JOB=unity7", "GDMSESSION=ubuntu", "GPG_AGENT_INFO=/home/alex/.gnupg/S.gpg-agent:0:1", "LANGUAGE=en_CA:en", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "INSTANCE=", "CONDARC=/home/alex/.julia/conda/3/envs/_ORCA_jl_/condarc-julia.yml", "_=/bin/julia", "XAUTHORITY=/home/alex/.Xauthority", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/alex", "TERM=xterm-256color", "SESSION=ubuntu", "XMODIFIERS=@im=ibus", "WINDOWID=73400330", "GNOME_KEYRING_CONTROL=", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "XDG_SESSION_TYPE=x11", "SHLVL=1", "UNITY_DEFAULT_PROFILE=unity", "QT_ACCESSIBILITY=1", "LOGNAME=alex", "JOB=unity-settings-daemon", "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-mFY1Fg3YCi", "XDG_SESSION_ID=c2", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_CURRENT_DESKTOP=Unity", "USER=alex", "JULIA_LOAD_PATH=@:/tmp/tmp7qt4Xw", "UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1725", "SESSION_MANAGER=local/Steak:@/tmp/.ICE-unix/2001,unix/Steak:/tmp/.ICE-unix/2001", "UPSTART_INSTANCE=", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "XDG_VTNR=7", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "PWD=/home/alex/Documents/vd", "GDM_LANG=en_CA", "PATH=/home/alex/bin:/home/alex/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "DISPLAY=:0", "OPENBLAS_MAIN_FREE=1", "QT4_IM_MODULE=xim", "XDG_MENU_PREFIX=gnome-", "SHELL=/bin/bash", "HOME=/home/alex", "CLUTTER_IM_MODULE=xim", "LESSCLOSE=/usr/bin/lesspipe %s %s", "SESSIONTYPE=gnome-session"]), ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run at ./process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::Symbol) at /home/alex/.julia/packages/Conda/CpuvI/src/Conda.jl:113
│  [6] add(::String, ::Symbol) at /home/alex/.julia/packages/Conda/CpuvI/src/Conda.jl:183
│  [7] top-level scope at none:0
│  [8] include at ./boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1038
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at /home/alex/.julia/dev/ORCA/deps/build.jl:5
└ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by stevengj** [comment]
@sglyon, maybe it is in `Conda.script_dir(env)`?  On Unix this is the same as `bin_dir`, but on Windows it is different from `bin_dir`.

Oh, the `The following packages are not available from current channels:  - plotly-orca` message above makes it sound like this package is simply unavailable on Windows at present.

**Comment by sglyon** [comment]
Good catch on the packages are not available line. @AlexYoooooo are you using a 32 bit architecture? From what I can tell the orca package is only released for 64 bit systems: https://anaconda.org/plotly/plotly-orca/files

I'm sorry team, but I'm not going to be able to personally debug the windows build issues because I don't have access to a windows machine. Could a windows user try out the suggestion from @stevengj to use `Conda.script_dir(env)` instead of `Conda.bin_dir(env)` on [this line](https://github.com/sglyon/ORCA.jl/blob/15f4793e66423faf861be175b834aa72bfb48158/deps/build.jl#L9) of the build.jl script?

**Comment by ezgikurt** [comment]
Hi @sglyon, I've tried changing the line but still getting the same error. The issue is when it builds, it doesn't add any other directories such as bin, Scripts etc. Even when I manually change paths.jl to direct it to orca.cmd file in the _ORCA_jl directory, it cannot execute that command because it fails to find the .exe file located at `"/.julia/conda/3/envs/_ORCA_jl_\orca_app\orca.exe" %*`

I've gone ahead an looked at the conda website and found the following:
![image](https://user-images.githubusercontent.com/32577002/52166904-2c211580-270b-11e9-8528-57a129aaebce.png)
The file that we add using Conda.add gets the highlighted folder, which seems pretty light compared to the Mac/Linux versions and also older versions of plotly-orca in Windows. 

So I've manually downloaded the older version of Conda, copied orca-app directory to _ORCA_jl and it was fixed. I also had to change paths.jl manually to direct it to "/.julia/conda/3/envs/_ORCA_jl_/orca.cmd %*` otherwise it was not working.  Now I can save using ORCA - a temporary fix for those using Windows. As far as I understand it's on the latest version of plotly-orca package missing the essential files.

**Comment by stevengj** [comment]
Sounds like you could just change the `deps/build.jl` file to do:
```jl
orca_cmd = Sys.is_windows() ? joinpath(Conda.prefix(env), "orca_app", "orca.exe") : joinpath(Conda.bin_dir(env), "orca")
```

**Comment by pbouffard** [comment]
FWIW this is also affecting me on a Mac.

**Comment by stevengj** [comment]
@pbouffard, have you tried the `master` version of ORCA.jl?  (That is, at the package prompt in Julia, do `checkout ORCA` and `build ORCA`.)

**Comment by sglyon** [comment]
@ezgikurt thanks for reporting that. I talked to people over at plotly and they've since released v1.2.1 that has a proper windows build.

Can you try again now and see if it grabs 1.2.1 AND if 1.2.1 has the files you need?

![image](https://user-images.githubusercontent.com/1001948/52228045-51cf2b80-287f-11e9-8aea-a48b04ba9ee3.png)

**Comment by ezgikurt** [comment]
Hi @sglyon i can confirm this is solved on my side now, changing the command in `build.jl` as suggested by @stevengj as:

`Sys.iswindows() ? joinpath(Conda.prefix(env), "orca_app", "orca.exe") : joinpath(Conda.bin_dir(env), "orca")`

Thanks everyone for the help!

**Comment by sglyon** [comment]
Great! Thank you everyone.

@ezgikurt would you be willing to open a pull request with that fix?

**Comment by ezgikurt** [comment]
Done, thank you!

**Comment by StefanPofahl** [comment]
I also struggle to get ORCA build properly on MS Windows 10:
I have removed the package and have reinstalled the package.
Attached is the build.log and the error messages inside the ATOM-console.

[build_orca.log](https://github.com/sglyon/ORCA.jl/files/4632366/build_orca.log)

[julia_ Pkg.build(_ORCA_).txt](https://github.com/sglyon/ORCA.jl/files/4632369/julia_.Pkg.build._ORCA_.txt)

**Comment by StefanPofahl** [comment]
I have tried to executre the two command lines mentioned in the build log-file, but this does not work:
[conda.exe_command_errors.txt](https://github.com/sglyon/ORCA.jl/files/4632498/conda.exe_command_errors.txt)

**Comment by StefanPofahl** [comment]
The workaround that worked for me (for ORCA v0.3.1):
I have installed Anaconda, I started the Anaconda cmd.exe configuration and gave the command:
`conda install --prefix "C:/Users/u16e45/.julia/conda/3/envs/_ORCA_jl_" --force-reinstall ORCA`

Now I can rebuild the ORCA-package inside Julia terminal :-)

**Comment by dcelisgarza** [comment]
> 
> 
> The workaround that worked for me (for ORCA v0.3.1):
> I have installed Anaconda, I started the Anaconda cmd.exe configuration and gave the command:
> `conda install --prefix "C:/Users/u16e45/.julia/conda/3/envs/_ORCA_jl_" --force-reinstall ORCA`
> 
> Now I can rebuild the ORCA-package inside Julia terminal :-)

This worked in the end but i had to run the following command in the Anaconda command prompt first

```
conda config --append channels conda-forge
```

To add the conda-forge channel as the default channels were not working. I found the answer in this stackexchange question:

[https://stackoverflow.com/a/48509426](https://stackoverflow.com/a/48509426)

**Comment by StefanPofahl** [comment]
I have the impression that this command was not useful for me:
`
(base) C:\Users\u16e45>conda config --append channels conda-forge
`
`
Warning: 'conda-forge' already in 'channels' list, moving to the bottom
`
I do not know why, but now julia does not start anylonger in the Atom
console (REPL).

**Comment by dcelisgarza** [comment]
It wasn't in my channels list. I ran that then ran your solution (I had to build ORCA in the julia REPL). I had julia break last night for me in the same way as you describe. It turned out to be an update.

**Comment by sglyon** [comment]
I believe this has been resolved!
